### ISSUE TITLE
smellscan-ts is not scanning the files for design smells

### ISSUE THREAD

**Issue by ayede** [abhipsb/smellscan-ts#1]
I added the plugin to scan my code to find out all the design smells in my code. But it is not showing me the smells. It shows the empty file as shown in screenshot.

![image](https://user-images.githubusercontent.com/9910877/131771641-5d48b779-c198-418c-ad43-e9de257005da.png)

Steps I did:

1. added plugin
2. right clicked on a folder in explorer
3. clicked on `Start SmellScan`
4. Then it shown me this empty file with single line

**Comment by abhipsb** [comment]
![image](https://user-images.githubusercontent.com/52134926/131781898-9d18886b-a295-4765-b430-6788f9c4ea6f.png)
@ayede try to run it on a inner folder which contains most of the ts files. Check the attached example pic from angular project, try to run it on the app folder of your project. Let me know further, thanks!

**Comment by ayede** [comment]
Thanks @abhipsb . It worked when I ran in other inner folders.

One suggestion I have. Can you improve the summary little bit more as shown in following screenshot?
This will be really helpful whoever will be using this extension. Because every one is interested in summary.
![image](https://user-images.githubusercontent.com/9910877/132114591-121d65f5-b65e-4dfc-b61a-ed88efa1696a.png)

And once done this, next thing we can do is little more detailed analysis - 
![image](https://user-images.githubusercontent.com/9910877/132114642-4c2201a9-8d25-4e91-b8d1-13eff322b644.png)

**Comment by abhipsb** [comment]
Hi @ayede, thanks for the feedback! I'll definitely try to incorporate your suggestion in future. By the way did you create these charts in excel?

For now I'll be closing this issue, and consider the suggestion for further improvement.
